# LC 1332 Remove Palindromic Subsequences


"""
A string is a subsequence of a given string if it is generated by deleting some characters of a given string without
changing its order. Note that a subsequence does not necessarily need to be contiguous.
e.g s = "bababbaab"
the following are all subsequences
"bbbbbb"
"aaaa"
"babab"
"baaab"
"""

"""
Problem Intuition

The important word in this problem is "subsequence", not "substring".

A subsequence does not have to be contiguous. We can choose any characters as long as their relative order remains the same.

The string contains only two possible characters: 'a' and 'b'.

Observation 1:
If the entire string is already a palindrome, then we can remove the whole string in a single operation because the
 entire string itself is a palindromic subsequence.

Answer = 1

Observation 2:
If the string is not a palindrome, we can always remove all 'a' characters in one operation because a string like 
"aaaa..." is always a palindrome. Then remove all 'b' characters in another operation because "bbbb..." is also a palindrome.

Therefore, every non-palindromic string can always be removed in exactly 2 operations.

Algorithm

1. If the string is empty, return 0.
2. Check whether the entire string is a palindrome using two pointers.
3. If it is a palindrome, return 1.
4. Otherwise, return 2.

Time Complexity:
O(n), where n is the length of the string, since we scan the string once to check whether it is a palindrome.

Space Complexity:
O(1), because only two pointers are used.
"""

"""
You are given a string s consisting only of letters 'a' and 'b'. In a single step you can remove one palindromic subsequence from s.

Return the minimum number of steps to make the given string empty.

A string is a subsequence of a given string if it is generated by deleting some characters of a given string without 
changing its order. Note that a subsequence does not necessarily need to be contiguous.

A string is called palindrome if is one that reads the same backward as well as forward.


Example 1:

Input: s = "ababa"
Output: 1
Explanation: s is already a palindrome, so its entirety can be removed in a single step.

Example 2:
Input: s = "abb"
Output: 2
Explanation: "abb" -> "bb" -> "". 
Remove palindromic subsequence "a" then "bb".

Example 3:
Input: s = "baabb"
Output: 2
Explanation: "baabb" -> "b" -> "". 
Remove palindromic subsequence "baab" then "b".
"""


def remove_palindromic_sub(s: str) -> int:
    if not s:
        return 0

    left, right = 0, len(s) - 1

    while left < right:
        if s[left] != s[right]:
            return 2
        left += 1
        right -= 1

    return 1


def main():
    s = input()
    print(remove_palindromic_sub(s))


if __name__ == "__main__":
    main()
