#LC 1332 Remove Palindromic Subsequences


"""
A string is a subsequence of a given string if it is generated by deleting some characters of a given string without
changing its order. Note that a subsequence does not necessarily need to be contiguous.
e.g s = "bababbaab"
the following are all subsequences
"bbbbbb"
"aaaa"
"babab"
"baaab"
"""

"""
You are given a string s consisting only of letters 'a' and 'b'. In a single step you can remove one palindromic subsequence from s.

Return the minimum number of steps to make the given string empty.

A string is a subsequence of a given string if it is generated by deleting some characters of a given string without 
changing its order. Note that a subsequence does not necessarily need to be contiguous.

A string is called palindrome if is one that reads the same backward as well as forward.


Example 1:

Input: s = "ababa"
Output: 1
Explanation: s is already a palindrome, so its entirety can be removed in a single step.

Example 2:
Input: s = "abb"
Output: 2
Explanation: "abb" -> "bb" -> "". 
Remove palindromic subsequence "a" then "bb".

Example 3:
Input: s = "baabb"
Output: 2
Explanation: "baabb" -> "b" -> "". 
Remove palindromic subsequence "baab" then "b".
"""

def remove_palindromic_sub(s: str) -> int:
    if not s:
        return 0

    left, right = 0, len(s) - 1

    while left < right:
        if s[left] != s[right]:
            return 2
        left += 1
        right -= 1

    return 1


def main():
    s = input()
    print(remove_palindromic_sub(s))


if __name__ == "__main__":
    main()
